; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"

; Libraries
libraries[JAIL][download][type] = "git"
libraries[JAIL][download][url] = "https://github.com/sebarmeli/JAIL.git"
libraries[JAIL][directory_name] = "JAIL"
libraries[JAIL][type] = "library"

libraries[openseadragon][download][type] = "get"
libraries[openseadragon][download][url] = "https://github.com/openseadragon/openseadragon/releases/download/v2.3.1/openseadragon-bin-2.3.1.zip"
libraries[openseadragon][directory_name] = "openseadragon"
libraries[openseadragon][type] = "library"

libraries[pdfjs][download][type] = "git"
libraries[pdfjs][download][url] = "https://github.com/mozilla/pdf.js.git"
libraries[pdfjs][directory_name] = "pdfjs"
libraries[pdfjs][type] = "library"

libraries[video-js][download][type] = "git"
libraries[video-js][download][url] = "https://github.com/videojs/video.js.git"
libraries[video-js][directory_name] = "video-js"
libraries[video-js][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"
