$block = array();
$block[] = array(
  'block_custom' => array(
  'info' => 'On Screen Keyboard', 
  'format' => 'full_html', 
  'title' => '', 
  'body' => '<div id=\"on-screen-keyboard\">
    <div id=\"tooltip-indicator\" title=\"You can move On Screen Keyboard by dragging from the edges.\"><i class=\"fas fa-arrows-alt\"></i></div>
    <div class=\"row on-screen-keyboard-title\">
        <a id=\"on-screen-keyboard-close\" href=\"#\"><i class=\"fas fa-window-close\"></i></a>
    </div>
    <div class=\"row ota-keyboard-line\" style=\"display: flex\">
        <button class=\"ota-keyboard btn btn-default character\" value=\"س\">س</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ژ\">ژ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ز\">ز</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ل\">ل</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ر\">ر</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ذ\">ذ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"د\">د</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"خ\">خ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ح\">ح</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"چ\">چ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ج\">ج</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ث\">ث</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ت\">ت</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"پ\">پ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ب\">ب</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ا\">ا</button>
    </div>
    <div class=\"row ota-keyboard-line\" style=\"display: flex\">
        <button class=\"ota-keyboard btn btn-default character\" value=\"ق\">ق</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ف\">ف</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ي\">ي</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ﻻ\">ﻻ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ه\">ه</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"و\">و</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ن\">ن</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"م\">م</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ك\">ك</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"غ\">غ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ع\">ع</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ظ\">ظ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ط\">ط</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ض\">ض</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ص\">ص</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ش\">ش</button>

    </div>
    <hr>
    <div class=\"row ota-keyboard-line\" style=\"display: flex\">
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"آ\">آ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"أ\">أ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"إ\">إ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ڭ\">ڭ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"گ\">گ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ۀ\">ۀ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ى\">ى</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ئ\">ئ</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ة\">ة</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\" ً\"> ً</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ء\">ء</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"ؤ\">ؤ</button>
    </div>
    <hr>
    <div class=\"row ota-keyboard-line\" style=\"display: flex\">
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٩\">٩</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٨\">٨</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٧\">٧</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٦\">٦</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٥\">٥</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٤\">٤</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٣\">٣</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٢\">٢</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"١\">١</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"٠\">٠</button>
    </div>
    <hr>
    <div class=\"row ota-keyboard-line\" style=\"display: flex\">
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character disabled\" value=\"\"></button>
        <button class=\"ota-keyboard btn btn-default character\" value=\" \" id=\"ota-keyboard-space\"><kbd>Space</kbd></button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"~\">~</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\'\"\'>\"</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"*\">*</button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"\" id=\"ota-keyboard-trash\" title=\"Delete all characters.\"><i class=\"fa fa-trash-o\" aria-hidden=\"true\"></i></button>
        <button class=\"ota-keyboard btn btn-default character\" value=\"\" id=\"ota-keyboard-delete\" title=\"Delete last character.\"><i class=\"fa fa-eraser\" aria-hidden=\"true\"></i></button>
    </div>
</div>', 
  'weight' => '0', 
  'cache' => '-1', 
  'custom' => '0', 
  'visibility' => '0', 
  'pages' => '', 
  'css_class' => '', 
  'status' => '1', 
  ),
);

$block[] = array(
  'block_custom' => array(
  'info' => 'Search Help', 
  'format' => 'full_html', 
  'title' => '', 
  'body' => '<div id=\"search-help\" class=\"modal fade\" role=\"dialog\">
    <div class=\"modal-dialog\">

        <!-- Modal content-->
        <div class=\"modal-content\">
            <div class=\"modal-body\">
                <div class=\"row\">
                     <h4><em>Broaden/narrow your search beyond exact matches by..</em></h4>
                     <ul class=\"list-group\">
                         <li class=\"list-group-item\">
                            <b>prepending/appending asterisk (*)</b>, so that your query matches all the words ending/beginning with the string you entered, respectively<br>
                            <em>mutefer*</em> matches any of <em>muteferriqa</em>, <em>muteferriqanınki</em>, <em>muteferiqa</em> and <em>mutefer</em>
                         </li>
                         <li class=\"list-group-item\">
                           <b>performing fuzzy-search using tilde (~)</b>, so that your query matches words that differ from your query string by the specified number of characters<br>
                           <em>muteferriqa~</em>, matches any of <em>muteferrika</em>, <em>miteferriqa</em>, <em>uteferriqa</em> and <em>umuteferriqa</em>
                         </li>
                         <li class=\"list-group-item\"><b>enclosing your query with quotation marks (\")</b>, so that query matches nothing but the exact phrase that you enter<br>
                         </li>
                     </ul> 
                     <h4><em>Enjoy the convenience of..</em></h4>
                     <ul class=\"list-group\">
                         <li class=\"list-group-item\">
                            <b>Autocomplete</b>, built into the site-wide search boxes, whereby you will see suggestions appearing below the search box while you are typing. It does not get activated before you enter at least three characters.
                         </li>
                         <li class=\"list-group-item\">
                           <b>Virtual keyboard for Ottoman Turkish</b>, that lets you enter Arabic characters when performing (full-text) searches in Ottoman Turkish. Please click the keyboard icon within a search box to bring it up.<br>
                         </li>
                    </ul> 
            </div>
        </div>
      </div>

    </div>
</div>', 
  'weight' => '-1', 
  'cache' => '-1', 
  'custom' => '0', 
  'visibility' => '0', 
  'pages' => '', 
  'css_class' => '', 
  'status' => '1', 
  ),
);


